services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "b1DepoQh5GUPRTfUFHSBi1p1BRvft/ozHsUrLM2kXfsKhAYGnIWBMbbSWLVu4IyOJ0yTBg4UJZ7ffaIo2YjLDUouR49DMph1RKTnmDLZtYWMveG8JyELYnohPXsPXgO17E6h1S4bOZX66eLaAjDOLa8BSmeWCDCf992IHg4Wsr//PuJ2EnT8/mnqU+Q7YF5Xo+ObXMcpPKaG+ivna65wFQ4oQNwi/vcGIaXu1kr6M5gQgW88NzDhZEQZnCv70TDACeE9n068ThIGFjSVFk4Z7mDnfU4Bmpo3IUkWuyGIIkgOBTjp3vXnqIQRHuMHae1V4DuD9qtTpIxoLRC/qUWngOdrKVvI9YuXU5hLCLUoRI74vT6eQ5h43EIAUDhSoSqNuYv87SW2mgq1AkOvdCo3z3/hWDDUrorLP9hzJsr4naPHkXlW/KnWRw0psUt1tnhjVI7HOME+DI/nXXfxDGaH10Kt9DDiEFimNg3hu8NdNGZjs3rviuZMgqZg0pHK84mQYPsJgALkWha+PTT+jDt7iUWB7pjb3d5CtahHTVgwT5n0i/mxPWeVxhWHdced1oq0o8CM/Zrl+/34V1ge2riEQesKQ71fzlWR5v75786xXxs6BHzH3IkbVqzKEWlMK5Fhz65LNnw2dedPZf25fzkOqfyi7ZNPDLhYruoFV7rfnSw="
    - secure: "Lib8a0BHUk+Sr9EH2ue6g/JaIujnW4qMSYGXYn0pOSIPI5BEnYVWwWaXC/SEaNoXgaV3Ne3numnBTzT6HHgtVuteQ3q7yoOfPzMvDR5eoT/GFatMUrMVel8TXtOxgn7ywgxA3sjTormhJb4f9ASOQHXG6XvgIr2+kOy9KQkRlIBRpGI/nSTzSExB9WiBP8wm5LpHcmo4Plf9+TU2+NtHshKb+d2watk4bkquILNrImJ7A/XG02QLxuQQ3xR0ITNrUu8KQ5TLELuWkxUkI/yAjQIK5lYzOxXPPFncQ29eHaLhsZRUin5dfmM00GrkG+NtswNdNIAbkhVq5N4GPUYMjHl4Qfs5frvMUUHRAFhimXsO+YsiVo1UTjHGHI6DB1FypJTzdJEUZXcbKlEB/dGJtFIlm22N+orXCEVYhbhpSpbjcaF2p8NoYzP3Oqw+iWAOy2Bn91WhymbG6teQbSIytkqNZ7Qr5FhLSFuT9v0xEIoXa/AHY0Liju1KigqojaOAb+S09fKii6YG2xWe62QCjrUneyaP4iqGfXW9c6l9I82EiQO/bZrG0ebGz0DgponYT2dfo1rpiUtnzx7DtjRcPpjErwcoSY3BGNiu8O1Fqc90Y2MnZnO4Z04ZF3beRpElvYlFudqEPs50biPCgIZvqiUPb/ZJoezL45jehQ8CxbA="

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Login into Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export GIT_SHA=`git rev-parse --short HEAD`
  - echo "Building commit $GIT_SHA"

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
      - docker-compose build db
      - docker-compose build test-postgresql
      - docker-compose run test-postgresql
    - stage: tests
      name: "Static Analysis"
      script:
      - docker-compose build static-analysis
      - docker-compose run static-analysis
    - stage: push
      script:
      - docker-compose build server
      - docker tag thoughts_server:latest edil3ra/thoughts-backend:$GIT_SHA
      - docker push edil3ra/thoughts-backend:$GIT_SHA
      - docker tag thoughts_server:latest edil3ra/thoughts-backend:$TRAVIS_BRANCH
      deploy:
      - provider: script
        script: docker push vince/thoughts-backend:$TRAVIS_BRANCH
        on:
          branch: master        
      - provider: script
        script: docker push vince/thoughts-backend:$TRAVIS_TAG
        on:
          tags: True
