services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "qom4SxWHXwAAFjmLf5lItHVpKyR6QMUddyTAApWEqjasuHHVMrSOZuA7fckYrKOnvZGiMowF3iGAU7lpOl0i0rZI1SRL7eslqO9o+JXJxmrWhZy6XYiNSKNDslcXA7T+xv39cyn22lLspVMCmCwTJxdF+BXsorMVL6u+pVmeCCQAr6bYjn/W5JFnsYO+d8DmUVB3K4Cx4p13axX4pxtQlG1QWxN7CfE9zPcbVnHBQ/YDxHOnDG8183io1gdewWCRFPvkI84cqdN3qj0SEmjT8c99qyN/I7uPKq6lusGEWMJBNLs8oNsZShtUKNaD9PozV0gIfb6Uzz1PQujUz7y9UG5S9aTtzrLES3Unns4mQ7kAgQIevb4gPFWnj/D+DHqGu8B91/b+spGwubNJ7fjAVLlPY9Lm2R3OXbAJ8SyVRsKOI6Gd7t7nOguXs7nlqg1Zr4Lclx0+WigqZXnAw6jocjTKd1af8bBcsuwX6nsUoE5cwClwX9Br59YFlYa+S9ZLaLTLBpZ2qBYmmvS2+xP6SKSlk95wu6oKyOq6GRI9xYdG3uCLWN0Wko4bCBqwObWCE7bZEpaUpN02VK0SL4qyaQJgq2bpXb6HRLJ6p5WHpNLhk0uD5/16VzZwC02Bkn2OTfBCPSR0Da4UWYmuOKNOjUVAdzPE9c5C2e03DQqsQIc="
    - secure: "KSjVbT/0Z/6mwqrZ91uKnMQm4nFPVAzcRlGVRP2Bh4mfg1SeVDq5JsdG5Lg+1OOTc1IDg0xrdl7EldD7NWrlWV5P4zdM5GKaJBIAVJvtzRshMzYEcdUHH+++pxT5tHw//vyNuY1ZwL6p0/jrdQIZQEUARChZRm/BAd+j34LVC0SiSn8darnNkDAQItr4e0aAqrdNhzc0bN88bMwYwhDs4FenCEsEL8nZAG45BEse6oeJGDh2/1Jg75pWnTxPe2UOhmoXOXIFfpMyy/zOCYJi2QPYWYUUUZYiMWTc6HONduFGMjG6wlJuT5nPQ58zyw16VRoWmUvFhTIDlsZukvzYNWx2ukHxkQieFnv148SVuoKyi+QBDNu8VdKwt5W4+CpbKvsa6Md8vRwhva/Ti3ajmGvlEoDtukGrQvkK8R5bSICqcAGARRmdWrPbBvpnD5rs82eDbVibftFoB5Au+iqsN1pxySmo0gvmS7IZxolsgQwGsRcJGf2TJYYOl8FB818z49nyBy3F0Grz3HyURc46VV6ZkZ9XtSfJmKaVRVT3OajbNVOyT1/Sz91At1boCt+tsFh+67dzgAWgUX0JUOutlB6Pf3h6JvKRR23YTSLNpaua8U9FSKBoP5Kwng7xpbOTZ9XyKOY2+fo+uWFWsnRwZ/zaM0KPAL97AMAa5lJ6Znw="

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Login into Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export GIT_SHA=`git rev-parse --short HEAD`
  - echo "Building commit $GIT_SHA"

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
      - docker-compose build db
      - docker-compose build test-postgresql
      - docker-compose run test-postgresql
    - stage: tests
      name: "Static Analysis"
      script:
      - docker-compose build static-analysis
      - docker-compose run static-analysis
    - stage: push
      script:
      - docker-compose build server
      - docker tag thoughts_server:latest edil3ra/thoughts-backend:$GIT_SHA
      - docker push edil3ra/thoughts-backend:$GIT_SHA
      - docker tag thoughts_server:latest edil3ra/thoughts-backend:$TRAVIS_BRANCH
      deploy:
      - provider: script
        script: docker push vince/thoughts-backend:$TRAVIS_BRANCH
        on:
          branch: master        
      - provider: script
        script: docker push vince/thoughts-backend:$TRAVIS_TAG
        on:
          tags: True
